import type { Pool } from "pg";
import { canonicalPool } from "../canonical-catalog/canonical-db.js";
import { normalizeKey, slugify } from "./knowledge-graph.utils.js";
import type { CreateKnowledgeEntity, KnowledgeEntity, KnowledgeEntityType, KnowledgeGraphRepository, KnowledgeRelationType, KnowledgeStats } from "./knowledge-graph.types.js";
const mapEntity=(r:any):KnowledgeEntity=>({id:r.id,type:r.type,key:r.key,name:r.name,slug:r.slug,description:r.description,metadata:r.metadata??{},createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()});
export class PgKnowledgeGraphRepository implements KnowledgeGraphRepository {
 constructor(private readonly pool:Pool=canonicalPool()){}
 async createEntity(input:CreateKnowledgeEntity){ const key=normalizeKey(input.key), slug=slugify(input.slug??input.name); const client=await this.pool.connect(); try {await client.query("BEGIN"); const r=await client.query(`INSERT INTO kg_entities(type,key,name,slug,description,metadata) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(type,key) DO UPDATE SET name=EXCLUDED.name,slug=EXCLUDED.slug,description=EXCLUDED.description,metadata=kg_entities.metadata||EXCLUDED.metadata,updated_at=now() RETURNING *`,[input.type,key,input.name,slug,input.description??null,input.metadata??{}]); for(const alias of input.aliases??[]) await client.query(`INSERT INTO kg_aliases(entity_id,alias,alias_normalized) VALUES($1,$2,$3) ON CONFLICT(entity_id,provider_key,alias_normalized) DO NOTHING`,[r.rows[0].id,alias,normalizeKey(alias)]); await client.query("COMMIT"); return mapEntity(r.rows[0]);} catch(e){await client.query("ROLLBACK");throw e;} finally{client.release();}}
 async listEntities(f:{type?:KnowledgeEntityType;q?:string;limit:number;offset:number}){const v:any[]=[];const w:string[]=[];if(f.type){v.push(f.type);w.push(`type=$${v.length}`)}if(f.q){v.push(`%${f.q}%`);w.push(`(name ILIKE $${v.length} OR key ILIKE $${v.length} OR slug ILIKE $${v.length})`)}v.push(f.limit);const li=v.length;v.push(f.offset);const oi=v.length;const r=await this.pool.query(`SELECT * FROM kg_entities ${w.length?`WHERE ${w.join(" AND ")}`:""} ORDER BY type,name LIMIT $${li} OFFSET $${oi}`,v);return r.rows.map(mapEntity)}
 async getEntity(id:string){const r=await this.pool.query(`SELECT * FROM kg_entities WHERE id=$1`,[id]);return r.rows[0]?mapEntity(r.rows[0]):null}
 async createRelation(i:{sourceId:string;targetId:string;type:KnowledgeRelationType;weight?:number;confidence?:number;metadata?:Record<string,unknown>}){const r=await this.pool.query(`INSERT INTO kg_relations(source_id,target_id,type,weight,confidence,metadata) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(source_id,target_id,type) DO UPDATE SET weight=EXCLUDED.weight,confidence=EXCLUDED.confidence,metadata=kg_relations.metadata||EXCLUDED.metadata,updated_at=now() RETURNING *`,[i.sourceId,i.targetId,i.type,i.weight??1,i.confidence??1,i.metadata??{}]);return r.rows[0]}
 async getProductGraph(id:string){const p=await this.pool.query(`SELECT id,provider_key,external_id,sku,name,status FROM canonical_products WHERE id=$1`,[id]);if(!p.rows[0])return null;const l=await this.pool.query(`SELECT l.relation_type,l.confidence,l.source,e.* FROM kg_product_links l JOIN kg_entities e ON e.id=l.entity_id WHERE l.canonical_product_id=$1 ORDER BY e.type,e.name`,[id]);return {product:p.rows[0],entities:l.rows.map((r:any)=>({...mapEntity(r),relationType:r.relation_type,confidence:Number(r.confidence),source:r.source}))}}
 async stats():Promise<KnowledgeStats>{const r=await this.pool.query(`SELECT (SELECT count(*)::int FROM kg_entities) entities,(SELECT count(*)::int FROM kg_relations) relations,(SELECT count(*)::int FROM kg_product_links) product_links,(SELECT count(*)::int FROM kg_aliases) aliases`);const b=await this.pool.query(`SELECT type,count(*)::int count FROM kg_entities GROUP BY type`);return {entities:r.rows[0].entities,relations:r.rows[0].relations,productLinks:r.rows[0].product_links,aliases:r.rows[0].aliases,byType:Object.fromEntries(b.rows.map((x:any)=>[x.type,x.count]))}}
}
