import type { RecommendationRuleResult } from "./engine/recommendation-core.types.js";
import type { DomainEvent } from "../../core/events/domain-events.js";
import type { RecommendationCompletedPayload } from "./recommendation.events.js";
import type { ResolvedSemanticConstraint, SemanticQueryResult, SemanticRecommendation } from "../knowledge-graph-v2/semantic-query.types.js";
export interface RecommendationRequest { readonly query:string; readonly limit?:number; readonly budget?:number; readonly quantity?:number; readonly currency?:string; readonly providerKey?:string; readonly categorySlugs?:readonly string[]; readonly knowledgeSlugs?:readonly string[]; readonly customizable?:boolean; readonly sustainability?:boolean; readonly profile?:string; readonly pipeline?:string; readonly sector?:string; readonly campaign?:string; readonly audience?:string; readonly debug?:boolean; }
export interface RecommendationEventPublisher { publish(event: DomainEvent<"recommendation.completed", RecommendationCompletedPayload>): Promise<void>; }
export interface RecommendationConstraintEvidence { readonly key:string; readonly label:string; readonly status:"MATCHED"|"VIOLATED"|"NEUTRAL"; readonly points:number; readonly reason?:string; readonly warning?:string; }
export interface RecommendationRankingFactor { readonly ruleId:string; readonly category:string; readonly points:number; readonly weight:number; readonly matched:boolean; }
export interface RecommendationExplanation { readonly headline:string; readonly confidence:number; readonly strengths:readonly string[]; readonly cautions:readonly string[]; readonly matchedConstraints:readonly RecommendationConstraintEvidence[]; readonly violatedConstraints:readonly RecommendationConstraintEvidence[]; readonly rankingFactors:readonly RecommendationRankingFactor[]; }
export interface RecommendationDiscardedAlternative { readonly productId:string; readonly name:string; readonly score:number; readonly reasons:readonly string[]; }
export interface RecommendationAnalysis { readonly returned:number; readonly discarded:number; readonly discardedAlternatives:readonly RecommendationDiscardedAlternative[]; }
export interface RecommendationItemResult { readonly productId:string; readonly providerKey?:string; readonly externalId?:string; readonly sku:string|null; readonly name:string; readonly slug:string; readonly description:string|null; readonly score:number; readonly unitPrice:number|null; readonly currency:string; readonly categories:readonly string[]; readonly knowledge:readonly string[]; readonly customizable:boolean; readonly reasons:readonly string[]; readonly warnings?:readonly string[]; readonly matchedEntities?:SemanticRecommendation["matchedEntities"]; readonly semanticScore?:number; readonly factors?:readonly RecommendationRuleResult[]; readonly explanation:RecommendationExplanation; }
export interface RecommendationResponse { readonly runId?:string; readonly query:string; readonly profile:string; readonly pipeline:string; readonly totalCandidates:number; readonly elapsedMs:number; readonly metrics:{readonly retrievalMs:number; readonly scoringMs:number; readonly candidatesRetrieved:number; readonly candidatesScored:number; readonly rulesEvaluated:number; readonly discardedByBudget:number; readonly candidatesWithValidPrice?:number; readonly candidatesMissingPrice?:number; readonly candidatesOverBudget?:number}; readonly interpreted:{constraints:ResolvedSemanticConstraint[];providerKey?:string;status:string;customizable?:boolean}; readonly diagnostics:SemanticQueryResult["diagnostics"]; readonly items:readonly RecommendationItemResult[]; readonly analysis:RecommendationAnalysis; }
