CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS kg_entities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),type text NOT NULL CHECK(type IN ('BRAND','CATEGORY','MATERIAL','TECHNIQUE','CERTIFICATE','ATTRIBUTE')),key text NOT NULL,name text NOT NULL,slug text NOT NULL,description text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(type,key),UNIQUE(type,slug));
CREATE INDEX IF NOT EXISTS kg_entities_type_name_idx ON kg_entities(type,name);
CREATE TABLE IF NOT EXISTS kg_aliases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),entity_id uuid NOT NULL REFERENCES kg_entities(id) ON DELETE CASCADE,provider_key text,alias text NOT NULL,alias_normalized text NOT NULL,language text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(entity_id,provider_key,alias_normalized));
CREATE INDEX IF NOT EXISTS kg_aliases_normalized_idx ON kg_aliases(alias_normalized);
CREATE TABLE IF NOT EXISTS kg_relations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_id uuid NOT NULL REFERENCES kg_entities(id) ON DELETE CASCADE,target_id uuid NOT NULL REFERENCES kg_entities(id) ON DELETE CASCADE,type text NOT NULL CHECK(type IN ('IS_A','RELATED_TO','COMPATIBLE_WITH','REQUIRES','CERTIFIED_BY','HAS_ATTRIBUTE')),weight numeric(8,4) NOT NULL DEFAULT 1,confidence numeric(5,4) NOT NULL DEFAULT 1,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(source_id<>target_id),UNIQUE(source_id,target_id,type));
CREATE INDEX IF NOT EXISTS kg_relations_source_idx ON kg_relations(source_id,type);CREATE INDEX IF NOT EXISTS kg_relations_target_idx ON kg_relations(target_id,type);
CREATE TABLE IF NOT EXISTS kg_product_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),canonical_product_id uuid NOT NULL REFERENCES canonical_products(id) ON DELETE CASCADE,entity_id uuid NOT NULL REFERENCES kg_entities(id) ON DELETE CASCADE,relation_type text NOT NULL CHECK(relation_type IN ('BRAND','CATEGORY','MATERIAL','TECHNIQUE','CERTIFICATE','ATTRIBUTE')),source text NOT NULL DEFAULT 'MANUAL',confidence numeric(5,4) NOT NULL DEFAULT 1,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(canonical_product_id,entity_id,relation_type));
CREATE INDEX IF NOT EXISTS kg_product_links_product_idx ON kg_product_links(canonical_product_id);CREATE INDEX IF NOT EXISTS kg_product_links_entity_idx ON kg_product_links(entity_id,relation_type);
