import { promises as fs } from "node:fs"; import path from "node:path"; import { randomUUID } from "node:crypto";
import { normalizeMarkingTechnique } from "./marking-technique.normalizer.js";
import type { ProductMarkingArea,ProductMarkingProfile,ProductMarkingTechnique,ProviderMarkingEvidence } from "./marking-intelligence.types.js";
const DATA_DIR=path.resolve(process.env.MARKING_INTELLIGENCE_DIR??"storage/marking-intelligence");
function safeId(v:string){return v.replace(/[^a-zA-Z0-9_.-]/g,"_")} function profilePath(id:string){return path.join(DATA_DIR,`${safeId(id)}.json`)} function clamp01(v:number){return Math.max(0,Math.min(1,Number.isFinite(v)?v:0))}
function normalizeArea(area:ProductMarkingArea):ProductMarkingArea{const p=area.placement;return {...area,id:area.id||randomUUID(),placement:{...p,x:clamp01(p.x),y:clamp01(p.y),width:clamp01(p.width),height:clamp01(p.height),...(typeof p.rotation==="number"?{rotation:p.rotation}:{})},techniques:area.techniques.map(t=>({...t,id:t.id||randomUUID()}))}}
export async function getMarkingProfile(productId:string){try{return JSON.parse(await fs.readFile(profilePath(productId),"utf8")) as ProductMarkingProfile}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw e}}
export async function saveMarkingProfile(input:Omit<ProductMarkingProfile,"updatedAt">|ProductMarkingProfile):Promise<ProductMarkingProfile>{const profile={...input,areas:input.areas.map(normalizeArea),updatedAt:new Date().toISOString()} as ProductMarkingProfile;await fs.mkdir(DATA_DIR,{recursive:true});await fs.writeFile(profilePath(profile.productId),JSON.stringify(profile,null,2),"utf8");return profile}
export async function mergeProviderMarkingProfile(provider:ProductMarkingProfile):Promise<ProductMarkingProfile>{
 const existing=await getMarkingProfile(provider.productId); if(!existing)return saveMarkingProfile(provider);
 // ADMIN wins. Provider refreshes only provider-owned areas; manual areas survive.
 const adminAreas=existing.areas.filter(a=>a.source==="ADMIN"||a.techniques.some(t=>t.source==="ADMIN"));
 return saveMarkingProfile({...provider,commercialImageUrl:existing.commercialImageUrl??provider.commercialImageUrl,mockupBaseImageUrl:existing.mockupBaseImageUrl??provider.mockupBaseImageUrl,areas:[...provider.areas,...adminAreas],updatedBy:"provider-sync+admin-override"});
}
const EVIDENCE_KEY=/(mark|print|printing|techni|personaliz|engr|laser|sublim|dtf|screen|pad|tampo|bord|transfer|area|size|max|width|height)/i;
export function collectProviderMarkingEvidence(value:unknown,max=250):ProviderMarkingEvidence[]{const found:ProviderMarkingEvidence[]=[];const seen=new Set<object>();const visit=(node:unknown,p0:string):void=>{if(found.length>=max||node==null)return;if(Array.isArray(node)){node.forEach((x,i)=>visit(x,`${p0}[${i}]`));return}if(typeof node!=="object")return;if(seen.has(node as object))return;seen.add(node as object);for(const [key,child] of Object.entries(node as Record<string,unknown>)){const p=p0?`${p0}.${key}`:key;if(EVIDENCE_KEY.test(key)&&(typeof child!=="object"||child===null||Array.isArray(child)))found.push({path:p,key,value:child});visit(child,p)}};visit(value,"");return found}
export function techniquesFromEvidence(evidence:readonly ProviderMarkingEvidence[]):ProductMarkingTechnique[]{const byCode=new Map<string,ProductMarkingTechnique>();for(const item of evidence){for(const value of Array.isArray(item.value)?item.value:[item.value]){if(typeof value!=="string"||value.trim().length<2)continue;const n=normalizeMarkingTechnique(value);if(n.code==="OTHER"&&!/(laser|sublim|dtf|serigraf|tampograf|bordad|transfer|digital|uv)/i.test(value))continue;if(!byCode.has(n.code))byCode.set(n.code,{id:randomUUID(),code:n.code,name:n.name,providerCode:value,source:"PROVIDER",providerRaw:item})}}return [...byCode.values()]}
