import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { CatalogProviderInput, CatalogProviderRecord } from "./catalog-provider.types.js";
const DEFAULT_PATH=process.env.CATALOG_PROVIDERS_FILE??".data/catalog-providers.json";
const MAKITO_DEFAULT:CatalogProviderInput={key:"makito",name:"Makito",description:"Catálogo de artículos promocionales y regalos personalizables.",status:"ACTIVE",baseUrl:"https://apis.makito.es",currency:"EUR",language:"es",taxPercent:21,defaultMarginPercent:35,credentials:{authType:"BASIC"},capabilities:{products:true,categories:true,media:true,prices:true,stock:true,documents:false,videos:false},importPolicy:{automatic:false,schedule:"0 3 * * *",batchSize:250,mediaConcurrency:4,createSnapshot:true,classifyProductBrain:true,downloadMedia:true,generateThumbnails:true,markMissingInactive:true,updatePrices:true,updateStock:true}};
function hideSecrets(provider:CatalogProviderRecord):CatalogProviderRecord{const credentials={...provider.credentials};for(const key of ["password","token","apiKey","clientSecret"] as const){if(credentials[key]) credentials[key]="********";}return {...provider,credentials};}
export class CatalogProviderService{
 constructor(private readonly filePath=DEFAULT_PATH){}
 private async loadRaw():Promise<CatalogProviderRecord[]>{try{return JSON.parse(await readFile(this.filePath,"utf8")) as CatalogProviderRecord[];}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT") throw error;const now=new Date().toISOString();const initial:CatalogProviderRecord[]=[{...MAKITO_DEFAULT,id:randomUUID(),productCount:0,activeProductCount:0,mediaCount:0,createdAt:now,updatedAt:now}];await this.save(initial);return initial;}}
 private async save(records:CatalogProviderRecord[]):Promise<void>{await mkdir(dirname(this.filePath),{recursive:true});const temp=`${this.filePath}.tmp`;await writeFile(temp,JSON.stringify(records,null,2),"utf8");await rename(temp,this.filePath);}
 async list(){return (await this.loadRaw()).map(hideSecrets);}
 async get(id:string){return (await this.loadRaw()).find(item=>item.id===id);}
 async create(input:CatalogProviderInput){const records=await this.loadRaw();if(records.some(item=>item.key===input.key)) throw new Error(`Ya existe el proveedor ${input.key}.`);const now=new Date().toISOString();const record:CatalogProviderRecord={...input,id:randomUUID(),productCount:0,activeProductCount:0,mediaCount:0,createdAt:now,updatedAt:now};await this.save([...records,record]);return hideSecrets(record);}
 async update(id:string,input:Partial<CatalogProviderInput>){const records=await this.loadRaw();const index=records.findIndex(item=>item.id===id);if(index<0) throw new Error("Proveedor no encontrado.");const current=records[index]!;const cleaned=input.credentials?Object.fromEntries(Object.entries(input.credentials).filter(([,v])=>v!==""&&v!=="********")):undefined;const updated:CatalogProviderRecord={...current,...input,credentials:cleaned?{...current.credentials,...cleaned}:current.credentials,capabilities:input.capabilities?{...current.capabilities,...input.capabilities}:current.capabilities,importPolicy:input.importPolicy?{...current.importPolicy,...input.importPolicy}:current.importPolicy,id:current.id,key:input.key??current.key,updatedAt:new Date().toISOString()};records[index]=updated;await this.save(records);return hideSecrets(updated);}
 async remove(id:string){const records=await this.loadRaw();const next=records.filter(item=>item.id!==id);if(next.length===records.length) throw new Error("Proveedor no encontrado.");await this.save(next);}
 async testConnection(id:string){const provider=await this.get(id);if(!provider) throw new Error("Proveedor no encontrado.");if(!provider.baseUrl) return {ok:false,message:"Falta la URL base.",checkedAt:new Date().toISOString()};try{const response=await fetch(provider.baseUrl,{method:"HEAD",signal:AbortSignal.timeout(8000)});return {ok:response.status<500,message:`Servidor accesible (HTTP ${response.status}).`,checkedAt:new Date().toISOString()};}catch(error){return {ok:false,message:error instanceof Error?error.message:"No se pudo conectar.",checkedAt:new Date().toISOString()};}}
}
