import { createHash } from "node:crypto";
import type { ComposerV2Candidate,ComposerV2Context,ComposerV2Item,ComposerV2Proposal,ComposerV2Result,ComposerV2Trace,ProposalItemRole } from "./composer-v2.types.js";

type Eval={c:ComposerV2Candidate;score:number;reasons:string[];warnings:string[];reject:string[]};
const overlap=(a?:readonly string[],b?:readonly string[])=>a?.filter(x=>b?.includes(x))??[];
function evalCandidate(c:ComposerV2Candidate,x:ComposerV2Context):Eval{let score=c.score??.5;const reasons:string[]=[];const warnings:string[]=[];const reject:string[]=[];
 if(x.excludedProductIds?.includes(c.id))reject.push("Producto excluido.");
 if(x.requireStock&&(c.stock??0)<=0)reject.push("Sin stock."); else if(c.stock!==undefined&&c.stock<=0){warnings.push("Sin stock.");score-=.25;}
 if(x.requirePersonalization&&!c.personalizationAvailable)reject.push("No admite personalización.");
 if(x.age!==undefined&&c.minAge!==undefined&&x.age<c.minAge)reject.push("Edad inferior al mínimo.");
 if(x.age!==undefined&&c.maxAge!==undefined&&x.age>c.maxAge)reject.push("Edad superior al máximo.");
 if(x.maxLeadTimeDays!==undefined&&(c.leadTimeDays??0)>x.maxLeadTimeDays)reject.push("Plazo excesivo.");
 const im=overlap(c.canonicalInterests,x.interests); if(im.length){score+=Math.min(.4,im.length*.12);reasons.push(`Afinidad: ${im.join(", ")}.`)}
 const mm=overlap(c.materials,x.preferredMaterials); if(mm.length){score+=Math.min(.18,mm.length*.08);reasons.push(`Material preferido: ${mm.join(", ")}.`)}
 if(c.personalizationAvailable){score+=.08;reasons.push("Admite personalización.")}
 return {c,score:Math.max(0,Math.min(1.5,score)),reasons,warnings,reject};}
const supports=(c:ComposerV2Candidate,r:ProposalItemRole)=>c.bundleRoles?.includes(r)??(r==="CORE"||r==="COMPLEMENT");
const compatible=(c:ComposerV2Candidate,items:Eval[])=>items.every(i=>!c.incompatibleWith?.includes(i.c.id)&&!i.c.incompatibleWith?.includes(c.id));
function story(items:ComposerV2Item[],x:ComposerV2Context){const who=x.recipientLabel??"esa persona especial";const hero=items.find(i=>i.role==="HERO")??items[0];const names=items.map(i=>i.name).join(", ");return {title:x.interests?.length?`${hero?.name??"Un recuerdo"} para disfrutar de ${x.interests.slice(0,2).join(" y ")}`:`${hero?.name??"Un recuerdo"} pensado para ${who}`,subtitle:x.occasion?`Una propuesta para ${x.occasion}, construida como una experiencia completa.`:"Una propuesta equilibrada, personalizable y preparada para emocionar.",story:`La propuesta une ${names}. Cada pieza cumple una función y el conjunto convierte el regalo en un recuerdo propio de ${who}.`,strengths:[`${items.length} elementos coordinados como una sola propuesta.`]};}
function metric(items:ComposerV2Item[],evals:Eval[],x:ComposerV2Context){const prices=items.map(i=>i.subtotal);const costs=evals.map(e=>e.c.cost);const totalPrice=prices.every(v=>v!==undefined)?prices.reduce((a,b)=>a+(b??0),0):undefined;const totalCost=costs.every(v=>v!==undefined)?costs.reduce((a,b)=>a+(b??0),0):undefined;const marginAmount=totalPrice!==undefined&&totalCost!==undefined?totalPrice-totalCost:undefined;const coverage=x.interests?.length?new Set(evals.flatMap(e=>overlap(e.c.canonicalInterests,x.interests))).size/x.interests.length:1;const coherence=Math.min(1,evals.reduce((a,e)=>a+e.score,0)/Math.max(1,evals.length));const commercial=Math.min(1,(marginAmount??0)/Math.max(1,totalPrice??1)+.5);const emotional=Math.min(1,.45+items.filter(i=>i.role==="MESSAGE"||i.role==="PACKAGING").length*.2);const final=coherence*.45+commercial*.25+emotional*.3;return {itemCount:items.length,...(totalPrice!==undefined?{totalPrice}:{}),...(totalCost!==undefined?{totalCost}:{}),...(marginAmount!==undefined?{marginAmount,marginPercent:totalPrice?marginAmount/totalPrice*100:0}:{}),withinBudget:x.budget===undefined||totalPrice===undefined||totalPrice<=x.budget,available:evals.every(e=>(e.c.stock??1)>0),personalizedItemCount:evals.filter(e=>e.c.personalizationAvailable).length,maximumLeadTimeDays:Math.max(0,...evals.map(e=>e.c.leadTimeDays??0)),interestCoverage:coverage,coherenceScore:coherence,commercialScore:commercial,emotionalScore:emotional,finalScore:final};}
export class ComposerV2Service{compose(candidates:readonly ComposerV2Candidate[],context:ComposerV2Context):ComposerV2Result{const traces:ComposerV2Trace[]=[{phase:"NORMALIZE",message:`${candidates.length} candidatos recibidos.`}];const evaluated=candidates.map(c=>evalCandidate(c,context));const eligible=evaluated.filter(e=>!e.reject.length).sort((a,b)=>b.score-a.score);traces.push({phase:"FILTER",message:`${eligible.length} candidatos elegibles.`});const min=Math.max(1,context.minItems??2),max=Math.max(min,Math.min(6,context.maxItems??4));const seeds=eligible.filter(e=>supports(e.c,"HERO")||supports(e.c,"CORE")).slice(0,12);const proposals:ComposerV2Proposal[]=[];
 for(const seed of seeds){const chosen:Eval[]=[seed];const roles:ProposalItemRole[]=[supports(seed.c,"HERO")?"HERO":"CORE"];for(const role of ["CORE","COMPLEMENT","MESSAGE","PACKAGING","OPTIONAL"] as ProposalItemRole[]){if(chosen.length>=max)break;const next=eligible.find(e=>!chosen.includes(e)&&supports(e.c,role)&&compatible(e.c,chosen));if(!next)continue;const prospective=[...chosen,next];const sum=prospective.reduce((a,e)=>a+(e.c.price??0),0);if(context.budget!==undefined&&sum>context.budget*1.15)continue;chosen.push(next);roles.push(role)}if(chosen.length<min)continue;
 const items=chosen.map((e,i):ComposerV2Item=>({productId:e.c.id,...(e.c.sku?{sku:e.c.sku}:{}),name:e.c.name,role:roles[i]??"COMPLEMENT",quantity:1,...(e.c.price!==undefined?{unitPrice:e.c.price,subtotal:e.c.price}:{}),...(e.c.imageUrl?{imageUrl:e.c.imageUrl}:{}),reasons:Object.freeze(e.reasons),warnings:Object.freeze(e.warnings)}));const s=story(items,context);const metrics=metric(items,chosen,context);const images=[...new Set(chosen.flatMap(e=>[e.c.imageUrl,...(e.c.images??[])].filter((v):v is string=>Boolean(v))))];const id=createHash("sha1").update(chosen.map(e=>e.c.id).sort().join("|")).digest("hex").slice(0,16);const proposalTraces:readonly ComposerV2Trace[]=Object.freeze([...traces,{phase:"BUNDLE_BUILD",message:`Lote ${id} construido con ${items.length} artículos.`},{phase:"CONSTRAINTS",message:metrics.withinBudget?"Dentro de presupuesto.":"Supera presupuesto."},{phase:"STORY",message:"Narrativa emocional generada."},{phase:"RANK",message:`Puntuación final ${metrics.finalScore.toFixed(3)}.`}]);proposals.push(Object.freeze({id,title:s.title,subtitle:s.subtitle,story:s.story,...(context.occasion?{occasionLine:`Creado especialmente para ${context.occasion}.`}:{}),...(images[0]?{imageUrl:images[0]}:{}),images:Object.freeze(images),items:Object.freeze(items),metrics,strengths:Object.freeze(s.strengths),warnings:Object.freeze(items.flatMap(i=>i.warnings)),traces:proposalTraces}))}
 const unique=new Map<string,ComposerV2Proposal>();for(const p of proposals.sort((a,b)=>b.metrics.finalScore-a.metrics.finalScore)){const k=p.items.map(i=>i.productId).sort().join("|");if(!unique.has(k))unique.set(k,p)}const out=[...unique.values()].slice(0,5);return Object.freeze({generatedAt:new Date().toISOString(),context,proposals:Object.freeze(out),rejectedCandidates:Object.freeze(evaluated.filter(e=>e.reject.length).map(e=>({productId:e.c.id,reasons:Object.freeze(e.reject)}))),diagnostics:Object.freeze({inputCandidates:candidates.length,eligibleCandidates:eligible.length,generatedBundles:unique.size,returnedProposals:out.length})});}}
export const defaultComposerV2=new ComposerV2Service();
