import { FormEvent, useEffect, useMemo, useState } from "react";

type Provider = {
  id:string; key:string; name:string; description:string; status:"ACTIVE"|"INACTIVE"|"ERROR"|"DRAFT"; baseUrl:string; currency:string; language:string; taxPercent:number; defaultMarginPercent:number;
  credentials:{authType:string;username?:string;password?:string;token?:string;apiKey?:string;clientId?:string;clientSecret?:string};
  capabilities:Record<string,boolean>; importPolicy:Record<string,boolean|string|number>; productCount:number; activeProductCount:number; mediaCount:number; lastSyncAt?:string; lastSyncStatus?:string; lastError?:string;
};

const emptyProvider:Omit<Provider,"id"|"productCount"|"activeProductCount"|"mediaCount">={key:"",name:"",description:"",status:"DRAFT",baseUrl:"",currency:"EUR",language:"es",taxPercent:21,defaultMarginPercent:35,credentials:{authType:"NONE"},capabilities:{products:true,categories:true,media:true,prices:true,stock:true,documents:false,videos:false},importPolicy:{automatic:false,schedule:"0 3 * * *",batchSize:250,mediaConcurrency:4,createSnapshot:true,classifyProductBrain:true,downloadMedia:true,generateThumbnails:true,markMissingInactive:true,updatePrices:true,updateStock:true}};

export function CatalogProvidersApp(){
 const [items,setItems]=useState<Provider[]>([]); const [selected,setSelected]=useState<Provider|undefined>(); const [draft,setDraft]=useState<any>(emptyProvider); const [message,setMessage]=useState(""); const [testing,setTesting]=useState(false);
 const load=()=>fetch('/api/v1/catalog-providers').then(r=>r.json()).then(v=>{setItems(v.items??[]);if(!selected&&v.items?.[0]){setSelected(v.items[0]);setDraft(v.items[0]);}});
 useEffect(()=>{void load();},[]);
 const totals=useMemo(()=>({active:items.filter(i=>i.status==='ACTIVE').length,products:items.reduce((a,b)=>a+(b.productCount||0),0),media:items.reduce((a,b)=>a+(b.mediaCount||0),0)}),[items]);
 const choose=(item:Provider)=>{setSelected(item);setDraft(JSON.parse(JSON.stringify(item)));setMessage("");};
 const createNew=()=>{setSelected(undefined);setDraft(JSON.parse(JSON.stringify(emptyProvider)));setMessage("");};
 const save=async(e:FormEvent)=>{e.preventDefault();setMessage("Guardando…");const response=await fetch(selected?`/api/v1/catalog-providers/${selected.id}`:'/api/v1/catalog-providers',{method:selected?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});if(!response.ok){const err=await response.json();setMessage(err.message??'No se pudo guardar.');return;}setMessage('Proveedor guardado.');await load();};
 const test=async()=>{if(!selected)return;setTesting(true);const response=await fetch(`/api/v1/catalog-providers/${selected.id}/test`,{method:'POST'});const data=await response.json();setMessage(data.message??'Prueba finalizada.');setTesting(false);};
 const remove=async()=>{if(!selected||!confirm(`Eliminar ${selected.name}?`))return;await fetch(`/api/v1/catalog-providers/${selected.id}`,{method:'DELETE'});setSelected(undefined);setDraft(emptyProvider);await load();};
 const update=(path:string,value:any)=>{setDraft((current:any)=>{const next=JSON.parse(JSON.stringify(current));const parts=path.split('.');let target=next;for(const part of parts.slice(0,-1))target=target[part];target[parts.at(-1)!]=value;return next;});};
 return <main className="providerAdminShell">
  <header className="providerAdminHeader"><div><a href="/admin">← Administración</a><small>OPERACIONES</small><h1>Proveedores</h1><p>Gestiona las fuentes de catálogo, sus credenciales y la forma en que se sincronizan con RecuerdArte.</p></div><button onClick={createNew}>+ Añadir proveedor</button></header>
  <section className="providerMetrics"><article><span>Proveedores</span><strong>{items.length}</strong></article><article><span>Activos</span><strong>{totals.active}</strong></article><article><span>Productos</span><strong>{totals.products.toLocaleString('es-ES')}</strong></article><article><span>Medios</span><strong>{totals.media.toLocaleString('es-ES')}</strong></article></section>
  <div className="providerAdminLayout"><aside className="providerList">{items.map(item=><button className={selected?.id===item.id?'is-selected':''} onClick={()=>choose(item)} key={item.id}><span className={`providerDot providerDot--${item.status.toLowerCase()}`} /><div><strong>{item.name}</strong><small>{item.key} · {item.status}</small></div><b>›</b></button>)}</aside>
  <form className="providerEditor" onSubmit={save}><div className="providerEditorTop"><div><small>{selected?'EDITAR PROVEEDOR':'NUEVO PROVEEDOR'}</small><h2>{draft.name||'Proveedor sin nombre'}</h2></div><span>{message}</span></div>
   <section><h3>Identidad y conexión</h3><div className="providerFormGrid"><label>Nombre<input value={draft.name??''} onChange={e=>update('name',e.target.value)} required /></label><label>Clave interna<input value={draft.key??''} onChange={e=>update('key',e.target.value.toLowerCase().replace(/[^a-z0-9-_]/g,''))} required /></label><label className="span2">Descripción<textarea value={draft.description??''} onChange={e=>update('description',e.target.value)} /></label><label className="span2">URL base<input value={draft.baseUrl??''} onChange={e=>update('baseUrl',e.target.value)} /></label><label>Estado<select value={draft.status} onChange={e=>update('status',e.target.value)}><option>ACTIVE</option><option>INACTIVE</option><option>ERROR</option><option>DRAFT</option></select></label><label>Autenticación<select value={draft.credentials.authType} onChange={e=>update('credentials.authType',e.target.value)}><option>NONE</option><option>BASIC</option><option>BEARER</option><option>API_KEY</option><option>OAUTH2</option></select></label><label>Usuario<input value={draft.credentials.username??''} onChange={e=>update('credentials.username',e.target.value)} /></label><label>Contraseña / secreto<input type="password" value={draft.credentials.password??''} onChange={e=>update('credentials.password',e.target.value)} placeholder="Dejar vacío para conservar" /></label></div></section>
   <section><h3>Condiciones comerciales</h3><div className="providerFormGrid"><label>Moneda<input value={draft.currency} onChange={e=>update('currency',e.target.value)} /></label><label>Idioma<input value={draft.language} onChange={e=>update('language',e.target.value)} /></label><label>IVA %<input type="number" value={draft.taxPercent} onChange={e=>update('taxPercent',Number(e.target.value))} /></label><label>Margen por defecto %<input type="number" value={draft.defaultMarginPercent} onChange={e=>update('defaultMarginPercent',Number(e.target.value))} /></label></div></section>
   <section><h3>Capacidades</h3><div className="providerChecks">{Object.entries(draft.capabilities??{}).map(([key,value])=><label key={key}><input type="checkbox" checked={Boolean(value)} onChange={e=>update(`capabilities.${key}`,e.target.checked)} /><span>{key}</span></label>)}</div></section>
   <section><h3>Política de importación</h3><div className="providerFormGrid"><label>Tamaño de lote<input type="number" value={draft.importPolicy.batchSize} onChange={e=>update('importPolicy.batchSize',Number(e.target.value))} /></label><label>Concurrencia imágenes<input type="number" value={draft.importPolicy.mediaConcurrency} onChange={e=>update('importPolicy.mediaConcurrency',Number(e.target.value))} /></label><label className="span2">Programación<input value={draft.importPolicy.schedule} onChange={e=>update('importPolicy.schedule',e.target.value)} /></label></div><div className="providerChecks">{Object.entries(draft.importPolicy??{}).filter(([,v])=>typeof v==='boolean').map(([key,value])=><label key={key}><input type="checkbox" checked={Boolean(value)} onChange={e=>update(`importPolicy.${key}`,e.target.checked)} /><span>{key}</span></label>)}</div></section>
   <footer className="providerActions"><div>{selected&&<><button type="button" className="secondary" onClick={test} disabled={testing}>{testing?'Comprobando…':'Probar conexión'}</button><a href={`/admin/catalog-imports?provider=${draft.key}`}>Importar ahora</a></>}</div><div>{selected&&<button type="button" className="danger" onClick={remove}>Eliminar</button>}<button type="submit">Guardar proveedor</button></div></footer>
  </form></div>
 </main>;
}
