import { useEffect, useMemo, useState } from "react";
import "./catalog-intelligence.css";

type Row = Record<string, unknown>;
type ViewMode = "table" | "mosaic";
type StudioTab = "diagnosis" | "editor" | "preview" | "history";

type Correction = {
  objectType?: string;
  giftRoles?: string[];
  interests?: Array<{ id: string; score: number; evidence: string[] }>;
  personalizationMethods?: string[];
  personalizationScore?: number;
  bundleScore?: number;
  premiumScore?: number;
  giftSuitabilityScore?: number;
  notes?: string;
};

const api = async <T,>(url: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(`/api/v1${url}`, { ...init, headers: { "content-type": "application/json", ...(init?.headers ?? {}) } });
  if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(typeof payload?.message === "string" ? payload.message : `HTTP ${response.status}`); }
  return response.json() as Promise<T>;
};
const text = (value: unknown): string => typeof value === "string" ? value : "";
const num = (value: unknown): number => typeof value === "number" ? value : 0;
const clean = (value: unknown): string => text(value).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const brainOf = (row?: Row): Row | undefined => row?.brain && typeof row.brain === "object" ? row.brain as Row : undefined;
const mediaOf = (row?: Row): Row[] => Array.isArray(row?.media) ? row.media.filter((item): item is Row => Boolean(item && typeof item === "object")) : [];
const imageOf = (row?: Row): string | undefined => mediaOf(row).map((item) => text(item.url)).find(Boolean) || text(row?.imageUrl) || undefined;
const stringArray = (value: unknown): string[] => Array.isArray(value) ? value.map(String) : [];
const scoredArray = (value: unknown): Array<{ id: string; score: number; evidence: string[] }> => Array.isArray(value) ? value.filter((item): item is Row => Boolean(item && typeof item === "object")).map(item => ({ id:text(item.id), score:num(item.score), evidence:stringArray(item.evidence) })) : [];

const NAV_GROUPS = [
  { label:"Panel principal", items:[["⌂","Dashboard","/admin"],["◉","Centro de Inteligencia","/admin/intelligence-center"],["✦","Laboratorio IA","/admin/ai-lab"]] },
  { label:"Catálogo", items:[["▣","Catálogo Inteligente","/admin/catalog-intelligence"],["⇩","Importaciones","/admin/catalog-imports"],["◎","Proveedores","/admin/providers"]] },
  { label:"Negocio", items:[["◫","Márgenes, tiempos y envíos","/admin/commercial-operations"],["▥","Estadísticas","/admin/statistics"]] },
  { label:"Sistema", items:[["⚙","Configuración","/admin/settings"],["↗","Volver a Rai","/"]] },
] as const;

function ProductImage({ row, large=false }: { row?: Row; large?: boolean }) {
  const src=imageOf(row); const [failed,setFailed]=useState(false); useEffect(()=>setFailed(false),[src]);
  if(!src||failed) return <div className={`ci2-imagePlaceholder ${large?"ci2-imagePlaceholder--large":""}`}><strong>RA</strong><span>Sin imagen</span></div>;
  return <img className={`ci2-productImage ${large?"ci2-productImage--large":""}`} src={src} alt={text(row?.name)||"Producto"} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>;
}
function Kpi({icon,value,label,tone}:{icon:string;value:number;label:string;tone:string}){return <article className="ci2-kpi"><span className={`ci2-kpiIcon ci2-kpiIcon--${tone}`}>{icon}</span><div><strong>{value.toLocaleString("es-ES")}</strong><span>{label}</span></div></article>}
function ToggleList({ values, selected, onChange }:{values:string[];selected:string[];onChange:(value:string[])=>void}){return <div className="ci2-choiceGrid">{values.map(value=><label key={value} className={selected.includes(value)?"is-selected":""}><input type="checkbox" checked={selected.includes(value)} onChange={event=>onChange(event.target.checked?[...selected,value]:selected.filter(item=>item!==value))}/><span>{value}</span></label>)}</div>}
function Metric({label,before,after}:{label:string;before:number;after?:number}){const final=after??before;return <div className="ci2-metric"><span>{label}</span><strong>{Math.round(final*100)} %</strong><i><b style={{width:`${Math.round(final*100)}%`}}/></i>{after!==undefined&&after!==before?<small>{Math.round(before*100)} % antes</small>:null}</div>}

export function CatalogIntelligenceApp(){
  const [stats,setStats]=useState<Row>(); const [items,setItems]=useState<Row[]>([]); const [selected,setSelected]=useState<Row>();
  const [studio,setStudio]=useState<Row>(); const [preview,setPreview]=useState<Row>(); const [correction,setCorrection]=useState<Correction>({});
  const [q,setQ]=useState(""); const [status,setStatus]=useState("REVIEW_REQUIRED"); const [provider,setProvider]=useState("makito"); const [viewMode,setViewMode]=useState<ViewMode>("table");
  const [tab,setTab]=useState<StudioTab>("diagnosis"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string>(); const [notice,setNotice]=useState<string>();
  async function load(){setBusy(true);setError(undefined);try{const params=new URLSearchParams({limit:"100"});if(q)params.set("q",q);if(status)params.set("status",status);if(provider)params.set("provider",provider);const [summary,list]=await Promise.all([api<Row>("/catalog-intelligence/stats"),api<{items:Row[]}>(`/catalog-intelligence/products?${params}`)]);setStats(summary);setItems(list.items);if(!selected&&list.items[0]?.id)void openProduct(String(list.items[0].id));}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo cargar el catálogo");}finally{setBusy(false)}}
  async function openProduct(id:string){try{const [product,studioData]=await Promise.all([api<Row>(`/catalog-intelligence/products/${id}`),api<Row>(`/catalog-intelligence/products/${id}/studio`)]);setSelected(product);setStudio(studioData);setPreview(undefined);const brain=studioData.brain as Row|undefined;setCorrection({objectType:text(brain?.objectType),giftRoles:stringArray(brain?.giftRoles),interests:scoredArray(brain?.interests),personalizationMethods:stringArray(brain?.personalizationMethods),personalizationScore:num(brain?.personalizationScore),bundleScore:num(brain?.bundleScore),premiumScore:num(brain?.premiumScore),giftSuitabilityScore:num(brain?.giftSuitabilityScore)});setTab("diagnosis");}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo abrir el producto")}}
  async function previewChanges(){if(!selected?.id)return;setBusy(true);try{setPreview(await api<Row>(`/catalog-intelligence/products/${selected.id}/studio/preview`,{method:"POST",body:JSON.stringify(correction)}));setTab("preview");}finally{setBusy(false)}}
  async function teach(){if(!selected?.id)return;setBusy(true);setNotice(undefined);try{await api(`/catalog-intelligence/products/${selected.id}/studio/teach`,{method:"POST",body:JSON.stringify({...correction,actor:"admin"})});setNotice("Rai ha aprendido esta corrección y el Product Brain se ha actualizado.");await openProduct(String(selected.id));await load();setTab("history");}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar el aprendizaje")}finally{setBusy(false)}}
  async function reclassify(){if(!selected?.id)return;setBusy(true);try{await api(`/catalog-intelligence/products/${selected.id}/reclassify`,{method:"POST",body:"{}"});setNotice("Product Brain recalculado conservando las correcciones administrativas.");await openProduct(String(selected.id));await load();}finally{setBusy(false)}}
  async function revert(historyId:string){if(!selected?.id||!confirm("¿Revertir el producto a esta versión?"))return;setBusy(true);try{await api(`/catalog-intelligence/products/${selected.id}/studio/revert/${historyId}`,{method:"POST",body:JSON.stringify({actor:"admin"})});setNotice("Versión restaurada.");await openProduct(String(selected.id));await load();}finally{setBusy(false)}}
  useEffect(()=>{void load()},[]);
  const brains=stats?.brains as Row|undefined; const products=stats?.products as Row|undefined; const selectedBrain=(studio?.brain as Row|undefined)??brainOf(selected); const after=preview?.after as Row|undefined;
  const interests=scoredArray(selectedBrain?.interests); const confidence=Math.round(num(selectedBrain?.classificationConfidence)*100); const roles=stringArray(selectedBrain?.giftRoles); const options=(studio?.options as Row|undefined)??{}; const history=Array.isArray(studio?.history)?studio.history.filter((x):x is Row=>Boolean(x&&typeof x==="object")):[]; const reviewReasons=stringArray(studio?.reviewReasons);
  return <div className="ci2-app"><aside className="ci2-sidebar"><a className="ci2-brand" href="/admin"><span>RA</span><div><strong>RecuerdArte</strong><small>Administración</small></div></a><nav>{NAV_GROUPS.map(group=><section key={group.label}><h3>{group.label}</h3>{group.items.map(([icon,label,href])=><a key={href} href={href} className={href==="/admin/catalog-intelligence"?"is-active":""}><span>{icon}</span>{label}</a>)}</section>)}</nav><footer>RecuerdArte RC7<br/><small>Product Brain Studio</small></footer></aside>
  <main className="ci2-main"><header className="ci2-topbar"><div><p>Centro de entrenamiento de Rai</p><h1>Catálogo Inteligente</h1><span>Inspecciona, corrige y enseña a Rai cómo entender cada producto.</span></div><div className="ci2-user"><span>R</span><div><strong>Rai Admin</strong><small>Administrador</small></div></div></header>{error&&<div className="ci2-alert">{error}</div>}{notice&&<div className="ci2-success">{notice}</div>}
  <section className="ci2-kpis"><Kpi icon="◇" value={num(products?.total)} label="Productos activos" tone="purple"/><Kpi icon="✣" value={num(brains?.ready)} label="Product Brain listos" tone="green"/><Kpi icon="△" value={num(brains?.review_required)} label="Necesitan revisión" tone="orange"/><Kpi icon="▥" value={num(products?.makito)} label="Productos Makito" tone="blue"/></section>
  <section className="ci2-filterCard"><label className="ci2-search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load()}} placeholder="Buscar por nombre, SKU o descripción..."/></label><label><span>Proveedor</span><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Todos</option><option value="makito">Makito</option></select></label><label><span>Estado</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="READY">Listos</option><option value="REVIEW_REQUIRED">Necesitan revisión</option></select></label><button className="ci2-primary" onClick={()=>void load()} disabled={busy}>{busy?"Cargando...":"Buscar"}</button></section>
  <section className="ci2-workspace"><div className="ci2-listPanel"><div className="ci2-panelToolbar"><div className="ci2-toggle"><button className={viewMode==="table"?"is-active":""} onClick={()=>setViewMode("table")}>☷ Lista</button><button className={viewMode==="mosaic"?"is-active":""} onClick={()=>setViewMode("mosaic")}>▦ Mosaico</button></div><span>{items.length} resultados</span></div>{viewMode==="table"?<div className="ci2-tableWrap"><table><thead><tr><th>Producto</th><th>Objeto</th><th>Confianza</th><th>Estado</th></tr></thead><tbody>{items.map(row=>{const brain=brainOf(row);const c=Math.round(num(brain?.classificationConfidence)*100);return <tr key={String(row.id)} className={String(selected?.id)===String(row.id)?"is-selected":""} onClick={()=>void openProduct(String(row.id))}><td><div className="ci2-productCell"><ProductImage row={row}/><div><strong>{text(row.name)}</strong><span>SKU: {text(row.sku)}</span><small>{text(row.provider_key)}</small></div></div></td><td>{text(brain?.objectType)||"Sin clasificar"}</td><td><div className="ci2-confidence"><span>{c||"—"}{c?"%":""}</span><i><b style={{width:`${c}%`}}/></i></div></td><td><span className={`ci2-status ci2-status--${text(row.brain_status).toLowerCase()}`}>{text(row.brain_status)||"SIN CLASIFICAR"}</span></td></tr>})}</tbody></table></div>:<div className="ci2-mosaic">{items.map(row=><button key={String(row.id)} onClick={()=>void openProduct(String(row.id))}><ProductImage row={row} large/><strong>{text(row.name)}</strong><span>{text(brainOf(row)?.objectType)||"Sin clasificar"}</span></button>)}</div>}</div>
  <aside className="ci2-detailPanel">{selected?<><div className="ci2-detailHeading"><div><small>SKU {text(selected.sku)}</small><h2>{text(selected.name)}</h2></div><button onClick={()=>void reclassify()} disabled={busy}>Recalcular Product Brain</button></div><div className="ci2-detailTop"><ProductImage row={selected} large/><dl><dt>Objeto</dt><dd>{text(selectedBrain?.objectType)||"Sin determinar"}</dd><dt>Roles</dt><dd><div className="ci2-tags">{roles.map(role=><span key={role}>{role}</span>)}</div></dd><dt>Confianza</dt><dd><div className="ci2-confidence ci2-confidence--wide"><span>{confidence}%</span><i><b style={{width:`${confidence}%`}}/></i></div></dd><dt>Estado</dt><dd><span className={`ci2-status ci2-status--${text(selectedBrain?.status).toLowerCase()}`}>{text(selectedBrain?.status)}</span></dd><dt>Versión</dt><dd>{text(selectedBrain?.version)}</dd></dl></div>
  <div className="ci2-tabs ci2-tabs--studio">{([['diagnosis','Diagnóstico'],['editor','Correcciones'],['preview','Vista previa'],['history','Historial']] as const).map(([key,label])=><button key={key} className={tab===key?"is-active":""} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==="diagnosis"&&<div className="ci2-studioBody"><section className="ci2-reviewBox"><h3>¿Por qué necesita revisión?</h3><ul>{reviewReasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section><div className="ci2-explanation"><article><h3>¿Qué entiende Rai?</h3><p>{clean(selected.description)||"No hay descripción disponible."}</p></article><article><h3>Métricas del Product Brain</h3><Metric label="Personalización" before={num(selectedBrain?.personalizationScore)}/><Metric label="Compatibilidad con lotes" before={num(selectedBrain?.bundleScore)}/><Metric label="Calidad como regalo" before={num(selectedBrain?.giftSuitabilityScore)}/></article></div><div className="ci2-interestSection"><h3>Intereses detectados</h3><div className="ci2-tags">{interests.length?interests.map(item=><span key={item.id}>{item.id} · {Math.round(item.score*100)}%</span>):<em>Sin intereses detectados</em>}</div></div></div>}
  {tab==="editor"&&<div className="ci2-editor"><label><span>Objeto físico</span><input list="object-types" value={correction.objectType??""} onChange={e=>setCorrection({...correction,objectType:e.target.value})}/><datalist id="object-types">{stringArray(options.objectTypes).map(value=><option key={value} value={value}/>)}</datalist></label><fieldset><legend>Roles de regalo</legend><ToggleList values={stringArray(options.roles)} selected={correction.giftRoles??[]} onChange={giftRoles=>setCorrection({...correction,giftRoles})}/></fieldset><fieldset><legend>Intereses y contextos</legend><ToggleList values={stringArray(options.interests)} selected={(correction.interests??[]).map(i=>i.id)} onChange={values=>setCorrection({...correction,interests:values.map(id=>({id,score:.95,evidence:["Corrección administrativa"]}))})}/></fieldset><fieldset><legend>Métodos de personalización</legend><ToggleList values={stringArray(options.personalizationMethods)} selected={correction.personalizationMethods??[]} onChange={personalizationMethods=>setCorrection({...correction,personalizationMethods})}/></fieldset><div className="ci2-sliderGrid">{([['personalizationScore','Personalización'],['bundleScore','Lotes'],['premiumScore','Calidad premium'],['giftSuitabilityScore','Calidad como regalo']] as const).map(([key,label])=><label key={key}><span>{label}: {Math.round((correction[key]??0)*100)}%</span><input type="range" min="0" max="1" step="0.01" value={correction[key]??0} onChange={e=>setCorrection({...correction,[key]:Number(e.target.value)})}/></label>)}</div><label><span>Notas del administrador</span><textarea value={correction.notes??""} onChange={e=>setCorrection({...correction,notes:e.target.value})} placeholder="Explica por qué haces esta corrección..."/></label><div className="ci2-editorActions"><button onClick={()=>void previewChanges()} disabled={busy}>Previsualizar cambios</button><button className="ci2-teach" onClick={()=>void teach()} disabled={busy}>🧠 Enseñar a Rai</button></div></div>}
  {tab==="preview"&&<div className="ci2-preview">{preview?<><div className="ci2-beforeAfter"><article><small>ANTES</small><h3>{text((preview.before as Row)?.objectType)}</h3><strong>{Math.round(num((preview.before as Row)?.classificationConfidence)*100)}%</strong></article><span>→</span><article className="is-after"><small>DESPUÉS</small><h3>{text(after?.objectType)}</h3><strong>{Math.round(num(after?.classificationConfidence)*100)}%</strong></article></div><section><h3>Cambios previstos</h3><ul>{stringArray(preview.changes).map(change=><li key={change}>{change}</li>)}</ul></section><section><h3>Estado después del cambio</h3><p><span className={`ci2-status ci2-status--${text(after?.status).toLowerCase()}`}>{text(after?.status)}</span></p>{stringArray(preview.reviewReasons).map(reason=><p key={reason}>{reason}</p>)}</section><button className="ci2-teach ci2-teach--wide" onClick={()=>void teach()} disabled={busy}>🧠 Confirmar y enseñar a Rai</button></>:<div className="ci2-emptySmall"><p>Aún no has generado una vista previa.</p><button onClick={()=>{setTab("editor")}}>Abrir correcciones</button></div>}</div>}
  {tab==="history"&&<div className="ci2-history">{history.length?history.map(entry=>{const before=entry.before as Row;const afterBrain=entry.after as Row;return <article key={text(entry.id)}><div><strong>{text(entry.action)==="REVERT"?"Versión restaurada":"Aprendizaje administrativo"}</strong><small>{new Date(text(entry.createdAt)).toLocaleString("es-ES")} · {text(entry.actor)}</small></div><p>{text(before?.objectType)} → <b>{text(afterBrain?.objectType)}</b></p><button onClick={()=>void revert(text(entry.id))}>Revertir a la versión anterior</button></article>}):<div className="ci2-emptySmall">Todavía no hay correcciones guardadas.</div>}</div>}
  </>:<div className="ci2-empty">Selecciona un producto para inspeccionarlo.</div>}</aside></section></main></div>
}
