import { useEffect, useMemo, useState } from "react";

type MarginRule={id:string;name:string;scope:string;scopeValue?:string;mode:string;value:number;minimumMarginPercent:number;minimumMarginAmount:number;active:boolean;priority:number};
type ProductionRule={id:string;name:string;scope:string;scopeValue?:string;preparationDays:number;productionDays:number;qualityControlDays:number;extraDays:number;businessDaysOnly:boolean;active:boolean;priority:number};
type ShippingZone={id:string;name:string;countries:string[];postalCodePrefixes:string[];active:boolean};
type ShippingMethod={id:string;name:string;carrier:string;zoneId:string;mode:string;basePrice:number;pricePerKg:number;freeFromOrderValue?:number;minDeliveryDays:number;maxDeliveryDays:number;trackingAvailable:boolean;active:boolean;priority:number};
type Data={version:number;settings:{currency:string;taxPercent:number;pricesIncludeTax:boolean;defaultWeightKg:number;packagingCost:number;paymentFeePercent:number;minimumOrderAmount:number;safetyProductionDays:number;cutOffHour:number};margins:MarginRule[];production:ProductionRule[];shippingZones:ShippingZone[];shippingMethods:ShippingMethod[]};
type Simulation={currency:string;unitPrice:number;subtotal:number;packagingCost:number;paymentFee:number;shippingCost:number;taxAmount:number;total:number;marginAmount:number;marginPercentOnPrice:number;productionDays:number;shippingDays:{min:number;max:number};estimatedDelivery:{from:string;to:string};appliedRules:string[];warnings:string[]};

const defaultMargin={name:"Nueva regla",scope:"GLOBAL",mode:"PERCENT_ON_COST",value:35,minimumMarginPercent:20,minimumMarginAmount:3,active:true,priority:100};
const defaultProduction={name:"Nueva regla",scope:"GLOBAL",preparationDays:1,productionDays:3,qualityControlDays:1,extraDays:0,businessDaysOnly:true,active:true,priority:100};
const defaultShipping={name:"Envío estándar",carrier:"",zoneId:"spain-peninsula",mode:"FLAT",basePrice:5.95,pricePerKg:0,freeFromOrderValue:60,minDeliveryDays:1,maxDeliveryDays:3,trackingAvailable:true,active:true,priority:100};

export function CommercialOperationsApp(){
 const [data,setData]=useState<Data>(); const [tab,setTab]=useState("summary"); const [error,setError]=useState<string>(); const [message,setMessage]=useState<string>();
 const [margin,setMargin]=useState<any>(defaultMargin); const [production,setProduction]=useState<any>(defaultProduction); const [shipping,setShipping]=useState<any>(defaultShipping);
 const [simulationInput,setSimulationInput]=useState({productCost:10,quantity:1,weightKg:0.5}); const [simulation,setSimulation]=useState<Simulation>();
 const load=async()=>{const response=await fetch("/api/v1/commercial-operations");if(!response.ok)throw new Error("No se pudo cargar la configuración comercial.");setData(await response.json() as Data)};
 useEffect(()=>{load().catch((e:Error)=>setError(e.message));},[]);
 const api=async(path:string,method:string,body?:unknown)=>{setError(undefined);setMessage(undefined);const response=await fetch(`/api/v1/commercial-operations${path}`,{method,headers:{"content-type":"application/json"},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.message??"No se pudo guardar.");setData(result as Data);setMessage("Cambios guardados.");};
 const money=(value:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:data?.settings.currency??"EUR"}).format(value);
 const localDate=(value:string)=>new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(value));
 const activeMethods=useMemo(()=>data?.shippingMethods.filter(x=>x.active).length??0,[data]);
 const simulate=async()=>{const response=await fetch("/api/v1/commercial-operations/simulate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(simulationInput)});const result=await response.json();if(!response.ok)throw new Error(result.message??"No se pudo simular.");setSimulation(result as Simulation)};
 if(!data)return <main className="commercialShell"><p>{error??"Cargando…"}</p></main>;
 return <main className="commercialShell">
  <header className="commercialHeader"><div><a href="/admin">← Administración</a><small>NEGOCIO Y OPERACIONES</small><h1>Márgenes, tiempos y envíos</h1><p>Reglas comerciales para calcular precios, rentabilidad, producción y fecha estimada de entrega.</p></div><aside><span>Configuración</span><strong>v{data.version}</strong><small>{data.settings.currency} · IVA {data.settings.taxPercent}%</small></aside></header>
  <nav className="commercialTabs">{[["summary","Resumen"],["margins","Márgenes"],["production","Producción"],["shipping","Envíos"],["simulator","Simulador"]].map(([id,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {message&&<div className="commercialNotice commercialNotice--ok">{message}</div>}{error&&<div className="commercialNotice commercialNotice--error">{error}</div>}
  {tab==="summary"&&<>
   <section className="commercialKpis"><article><span>Reglas de margen</span><strong>{data.margins.filter(x=>x.active).length}</strong><small>{data.margins.length} configuradas</small></article><article><span>Reglas de producción</span><strong>{data.production.filter(x=>x.active).length}</strong><small>{data.settings.safetyProductionDays} días de seguridad</small></article><article><span>Métodos de envío</span><strong>{activeMethods}</strong><small>{data.shippingZones.length} zonas</small></article><article><span>Pedido mínimo</span><strong>{money(data.settings.minimumOrderAmount)}</strong><small>Packaging {money(data.settings.packagingCost)}</small></article></section>
   <section className="commercialSettings"><h2>Parámetros generales</h2><div className="commercialGrid">{Object.entries(data.settings).filter(([key])=>key!=="updatedAt").map(([key,value])=><label key={key}><span>{key}</span>{typeof value==="boolean"?<input type="checkbox" checked={value} onChange={e=>setData({...data,settings:{...data.settings,[key]:e.target.checked}})}/>:<input value={String(value)} type={typeof value==="number"?"number":"text"} onChange={e=>setData({...data,settings:{...data.settings,[key]:typeof value==="number"?Number(e.target.value):e.target.value}})}/>}</label>)}</div><button className="commercialPrimary" onClick={()=>api("/settings","PATCH",data.settings)}>Guardar parámetros generales</button></section>
  </>}
  {tab==="margins"&&<section className="commercialTwoColumns"><div><h2>Reglas de margen</h2><div className="commercialCards">{data.margins.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.scope}{item.scopeValue?` · ${item.scopeValue}`:""}</span></div><b>{item.mode==="FIXED"?money(item.value):`${item.value}%`}</b><small>Mínimo: {item.minimumMarginPercent}% / {money(item.minimumMarginAmount)}</small><div><button onClick={()=>setMargin(item)}>Editar</button><button onClick={()=>api(`/margins/${item.id}`,"DELETE")}>Eliminar</button></div></article>)}</div></div><RuleForm title="Regla de margen" value={margin} setValue={setMargin} fields={["name","scope","scopeValue","mode","value","minimumMarginPercent","minimumMarginAmount","priority"]} onSave={()=>api("/margins","POST",margin)} onNew={()=>setMargin(defaultMargin)}/></section>}
  {tab==="production"&&<section className="commercialTwoColumns"><div><h2>Tiempos de realización</h2><div className="commercialCards">{data.production.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.scope}{item.scopeValue?` · ${item.scopeValue}`:""}</span></div><b>{item.preparationDays+item.productionDays+item.qualityControlDays+item.extraDays} días</b><small>Preparación {item.preparationDays} · Producción {item.productionDays} · Control {item.qualityControlDays}</small><div><button onClick={()=>setProduction(item)}>Editar</button><button onClick={()=>api(`/production/${item.id}`,"DELETE")}>Eliminar</button></div></article>)}</div></div><RuleForm title="Regla de producción" value={production} setValue={setProduction} fields={["name","scope","scopeValue","preparationDays","productionDays","qualityControlDays","extraDays","priority"]} onSave={()=>api("/production","POST",production)} onNew={()=>setProduction(defaultProduction)}/></section>}
  {tab==="shipping"&&<section className="commercialTwoColumns"><div><h2>Métodos de envío</h2><div className="commercialCards">{data.shippingMethods.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.carrier||"Sin transportista"}</span></div><b>{money(item.basePrice)}</b><small>{item.minDeliveryDays}–{item.maxDeliveryDays} días · Gratis desde {item.freeFromOrderValue?money(item.freeFromOrderValue):"—"}</small><div><button onClick={()=>setShipping(item)}>Editar</button><button onClick={()=>api(`/shipping-methods/${item.id}`,"DELETE")}>Eliminar</button></div></article>)}</div></div><RuleForm title="Método de envío" value={shipping} setValue={setShipping} fields={["name","carrier","zoneId","mode","basePrice","pricePerKg","freeFromOrderValue","minDeliveryDays","maxDeliveryDays","priority"]} onSave={()=>api("/shipping-methods","POST",shipping)} onNew={()=>setShipping(defaultShipping)}/></section>}
  {tab==="simulator"&&<section className="commercialSimulator"><div><h2>Simulador de precio y entrega</h2><div className="commercialGrid">{Object.entries(simulationInput).map(([key,value])=><label key={key}><span>{key}</span><input type="number" value={value} onChange={e=>setSimulationInput({...simulationInput,[key]:Number(e.target.value)})}/></label>)}</div><button className="commercialPrimary" onClick={()=>simulate().catch((e:Error)=>setError(e.message))}>Calcular</button></div>{simulation&&<div className="commercialResult"><h2>Resultado</h2><dl><dt>Precio unitario</dt><dd>{money(simulation.unitPrice)}</dd><dt>Subtotal</dt><dd>{money(simulation.subtotal)}</dd><dt>Envío</dt><dd>{money(simulation.shippingCost)}</dd><dt>IVA</dt><dd>{money(simulation.taxAmount)}</dd><dt>Total</dt><dd><strong>{money(simulation.total)}</strong></dd><dt>Margen</dt><dd>{money(simulation.marginAmount)} · {simulation.marginPercentOnPrice}%</dd><dt>Producción</dt><dd>{simulation.productionDays} días</dd><dt>Entrega estimada</dt><dd>{localDate(simulation.estimatedDelivery.from)} – {localDate(simulation.estimatedDelivery.to)}</dd></dl><p>Reglas: {simulation.appliedRules.join(" · ")}</p>{simulation.warnings.map(w=><em key={w}>{w}</em>)}</div>}</section>}
 </main>
}

function RuleForm({title,value,setValue,fields,onSave,onNew}:{title:string;value:any;setValue:(v:any)=>void;fields:string[];onSave:()=>void;onNew:()=>void}){return <aside className="commercialForm"><div><h2>{title}</h2><button onClick={onNew}>Nueva</button></div>{fields.map(key=><label key={key}><span>{key}</span>{key==="scope"?<select value={value[key]??"GLOBAL"} onChange={e=>setValue({...value,[key]:e.target.value})}>{["GLOBAL","PROVIDER","CATEGORY","PRODUCT","TECHNIQUE"].map(x=><option key={x}>{x}</option>)}</select>:key==="mode"?<select value={value[key]??"PERCENT_ON_COST"} onChange={e=>setValue({...value,[key]:e.target.value})}>{["PERCENT_ON_COST","PERCENT_ON_PRICE","FIXED","FLAT","BY_WEIGHT","BY_ORDER_VALUE","PROVIDER"].map(x=><option key={x}>{x}</option>)}</select>:<input type={typeof value[key]==="number"?"number":"text"} value={value[key]??""} onChange={e=>setValue({...value,[key]:typeof value[key]==="number"?Number(e.target.value):e.target.value})}/>}</label>)}<button className="commercialPrimary" onClick={onSave}>Guardar</button></aside>}
