import { useEffect, useMemo, useState } from "react";

type Stage = { id: string; label: string; status: string; durationMs: number; summary: string; input?: unknown; output?: unknown };
type Trace = { id: string; createdAt: string; scenario: { message?: string }; giftProfile: Record<string, unknown>; recommendations: readonly unknown[]; stages: readonly Stage[]; totals: { durationMs: number; recommendations: number; warnings: number } };

export function IntelligenceCenterApp() {
  const [traces, setTraces] = useState<readonly Trace[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/v1/intelligence-center/traces?limit=100").then(async (response) => { if (!response.ok) throw new Error("No se pudieron cargar las trazas."); return response.json() as Promise<{ items: Trace[] }>; }).then((value) => { setTraces(value.items); setSelectedId((current) => current ?? value.items[0]?.id); }).catch((value) => setError(value instanceof Error ? value.message : "Error")); }, []);
  const selected = useMemo(() => traces.find((trace) => trace.id === selectedId), [traces, selectedId]);
  return <main className="intelligenceShell intelligenceCenterShell">
    <header className="intelligenceHeader"><a href="/admin">← Administración</a><div><small>CENTRO DE INTELIGENCIA</small><h1>El recorrido completo de cada decisión.</h1><p>Inspecciona entrada, perfil, catálogo, ranking y semillas creativas en una misma traza.</p></div><a href="/admin/ai-lab">Abrir Laboratorio IA →</a></header>
    {error && <p className="intelligenceError">{error}</p>}
    <section className="traceLayout"><aside className="traceList"><div className="panelTitle"><div><small>HISTORIAL</small><h2>Trazas</h2></div><span>{traces.length}</span></div>{traces.map((trace) => <button className={selectedId === trace.id ? "selected" : ""} key={trace.id} onClick={() => setSelectedId(trace.id)}><strong>{trace.scenario.message ?? "Escenario"}</strong><span>{new Date(trace.createdAt).toLocaleString("es-ES")}</span><small>{trace.totals.recommendations} resultados · {trace.totals.durationMs} ms</small></button>)}</aside>
      <section className="traceDetail">{selected ? <><div className="traceHero"><div><small>ENTRADA</small><h2>{selected.scenario.message}</h2></div><div><strong>{selected.totals.durationMs} ms</strong><span>duración total</span></div></div>{(() => { const journeyStage = selected.stages.find((stage) => stage.id === "journey-intelligence"); const model = (journeyStage?.output as { giftModel?: { quality?: { score?: number; dimensions?: readonly { id: string; label: string; score: number; status: string }[] }; readiness?: { level?: string; canOfferButton?: boolean } } } | undefined)?.giftModel; return model ? <section className="giftModelInspector"><header><div><small>GIFT MODEL</small><h3>Calidad del Journey: {model.quality?.score ?? 0}%</h3></div><span>{model.readiness?.level ?? "NOT_READY"}</span></header><div className="giftModelHeatmap">{model.quality?.dimensions?.map((dimension) => <div key={dimension.id}><label><span>{dimension.label}</span><strong>{dimension.score}%</strong></label><progress max={100} value={dimension.score} /></div>)}</div></section> : null; })()}<div className="intelligencePipeline">{selected.stages.map((stage, index) => <article key={stage.id}><div className="pipelineIndex">{String(index + 1).padStart(2, "0")}</div><div className="pipelineBody"><header><div><small>{stage.status}</small><h3>{stage.label}</h3></div><span>{stage.durationMs} ms</span></header><p>{stage.summary}</p><details><summary>Ver datos de la etapa</summary><div className="pipelineJson"><section><small>ENTRADA</small><pre>{JSON.stringify(stage.input ?? null, null, 2)}</pre></section><section><small>SALIDA</small><pre>{JSON.stringify(stage.output ?? null, null, 2)}</pre></section></div></details></div></article>)}</div></> : <div className="emptyIntelligence">Todavía no hay trazas. Ejecuta primero un escenario en el Laboratorio IA.</div>}</section></section>
  </main>;
}
